include: package:lints/recommended.yaml

formatter:
  page_width: 80

linter:
  rules:
    - package_api_docs
    - public_member_api_docs
    - sort_pub_dependencies
    - require_trailing_commas

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true
  errors:
    missing_return: error
    missing_required_param: error
  exclude:
    - 'build/**'
